type Query {
  quiz (id: ID!): Quiz
  quizzes(limit: Int, offset: Int): [Quiz]
}

type Mutation {
  createQuiz (input: createQuizInput!): Quiz
  createQuestion (input: createQuestionInput!): Question
  createOptions (input: [createOptionInput]!): [Option]
  addOption (input: createOptionInput!): Option
}

type Quiz {
  quiz_id: ID!
  name: String!
  benchmark: Int!
  questions: [Question]
}

type Question {
  question_id: ID!
  question: String!
  quiz: Quiz!
  options: [Option]
}

type Option {
  option_id: ID!
  answer: String!
  question: Question!
  isCorrect: Boolean!
}

input createQuestionInput {
  quiz_id: ID!
  question: String!
}

input createOptionInput {
  question_id: ID
  answer: String
  is_correct: Boolean
}

input createQuizInput {
  name: String
  benchmark: Int
}